import Head from 'next/head'
import { useState } from 'react'
import axios from '../../axios'
import Link from 'next/link'
import Loader from '../../components/Loader'
import { toast, ToastContainer } from 'react-toastify';

export default function Home() {

    const [phone, setPhone] = useState('')
    const [phoneError, setPhoneError] = useState(false)
    const [phoneErrorMsg, setPhoneErrorMsg] = useState('')

    const [email, setEmail] = useState('')
    const [emailError, setEmailError] = useState(false)
    const [emailErrorMsg, setEmailErrorMsg] = useState('')

    const [name, setName] = useState('')
    const [nameError, setNameError] = useState(false)
    const [nameErrorMsg, setNameErrorMsg] = useState('')

    const [showLoader, setShowLoader] = useState(false)

    const phoneHandler = (text) =>{
        setPhone(text) 
        if (text == '') {
          setPhoneError(true) 
          setPhoneErrorMsg('Please enter a phone number') 
          return;
        } else if (!(/^[0-9\s]*$/.test(text)) || text.length > 10 || text.length < 10) {
          setPhoneError(true)
          setPhoneErrorMsg('please enter a valid phone number')  
          return;
        } else {
          setPhoneError(false)
          setPhoneErrorMsg('')  
        }
      }

      const emailHandler = (text) =>{
        setEmail(text) 
        if (text == '') {
          setEmailError(true) 
          setEmailErrorMsg('Please enter a email') 
          return;
        } else if (!(/^([A-Z|a-z|0-9](\.|_){0,1})+[A-Z|a-z|0-9]\@([A-Z|a-z|0-9])+((\.){0,1}[A-Z|a-z|0-9]){2}\.[a-z]{2,3}$/.test(text))) {
          setEmailError(true)
          setEmailErrorMsg('please enter a valid email')  
          return;
        } else {
          setEmailError(false)
          setEmailErrorMsg('')  
        }
      }

      const nameHandler = (text) =>{
        setName(text) 
        if (text == '') {
          setNameError(true) 
          setNameErrorMsg('Please enter a name') 
          return;
        } else if (!(/^[a-zA-Z\s]*$/.test(text))) {
          setNameError(true)
          setNameErrorMsg('please enter a valid name')  
          return;
        } else {
          setNameError(false)
          setNameErrorMsg('')  
        }
      }

      const register = (e) =>{
        e.preventDefault()

        if (name == '') {
            setNameError(true) 
            setNameErrorMsg('Please enter a name') 
            return;
        }
        if (email == '') {
            setEmailError(true) 
            setEmailErrorMsg('Please enter a email')
            return;
        }
        if (phone == '') {
            setPhoneError(true) 
            setPhoneErrorMsg('Please enter a phone number') 
            return;
        }
        if(nameError){
            setNameError(true) 
            setNameErrorMsg('Please enter a name')
            return;
        }
        if(phoneError){
            setPhoneError(true) 
          setPhoneErrorMsg('Please enter a phone number')
            return;
        }
        if(emailError){
            setEmailError(true) 
            setEmailErrorMsg('Please enter a email')
            return;
        }
        
        const formData = new FormData();
        formData.append('phone',phone);
        formData.append('email',email);
        formData.append('name',name);
        setShowLoader(true)
        axios.post('/auth/register',formData)
        .then(res => {
            setShowLoader(false)
            // console.log(res);
            toast.success('Registered Successfully.', {
                position: "top-right",
                autoClose: 5000,
                hideProgressBar: false,
                closeOnClick: true,
                pauseOnHover: true,
                toastId: new Date()
              });
              setName('')
              setEmail('')
              setPhone('')
        })
        .catch(err => {
            setShowLoader(false)
            // console.log(err);
            toast.error(err?.response?.data?.data, {
                position: "top-right",
                autoClose: 5000,
                hideProgressBar: false,
                closeOnClick: true,
                pauseOnHover: true,
                toastId: new Date()
              });
              
        })
        setPhoneError(false)
        setPhoneErrorMsg('') 
        setNameError(false)
          setNameErrorMsg('')
        setEmailError(false)
          setEmailErrorMsg('')
      }

    return (
        <div className=''>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main id="main-app">
                {showLoader?<Loader />:null}
                <div id="main-wrapper">

                    <div className="gray py-3">
                        <div className="container">
                            <div className="row align-items-start justify-center">
                                <div className="colxl-12 col-sm-8 col-md-6 col-lg-3 text-center">
                                    <a className="nav-brand" href="#">
                                        <img src="/img/logo.png" className="logo" alt="" />
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <section className="middle">
                        <div className="container">
                            <div className="row align-items-start justify-center">


                                <div className="col-xl-6 col-lg-6 col-md-12 col-sm-12 mfliud">
                                    <h1 className="mb-3 ft-bold lg-heading text-center">Register</h1>
                                    <form className="border p-3 rounded">

                                        <div className="row">
                                            <div className="form-group col-md-6">
                                                <label>Name *</label>
                                                <input type="text" className="form-control" name="name" placeholder="Name" value={name} onChange={(e)=>nameHandler(e.target.value)} />
                                                {nameError ? <i style={{ color: 'red' }}>{nameErrorMsg}</i>:null}
                                            </div>
                                            <div className="form-group col-md-6">
                                                <label>Phone Number</label>
                                                <input type="text" className="form-control" name="phone" placeholder="Phone Number*" value={phone} onChange={(e)=>phoneHandler(e.target.value)} />
                                                {phoneError ? <i style={{ color: 'red' }}>{phoneErrorMsg}</i>:null}
                                            </div>
                                        </div>

                                        <div className="form-group">
                                            <label>Email *</label>
                                            <input type="text" className="form-control" name="email" placeholder="Email*" value={email} onChange={(e)=>emailHandler(e.target.value)} />
                                            {emailError ? <i style={{ color: 'red' }}>{emailErrorMsg}</i>:null}
                                        </div>

                                        <div className="form-group">
                                            <p>By registering your details, you agree with our Terms & Conditions, and Privacy and Cookie Policy.</p>
                                        </div>

                                        <div className="form-group">
                                            <div className="d-flex align-items-center justify-content-between">
                                                <div className="flex-1">

                                                </div>
                                                <Link href="/" className="eltio_k2">
                                                    <a>Login</a>
                                                </Link>
                                            </div>
                                        </div>

                                        <div className="form-group">
                                            <button onClick={(e)=>register(e)} className="btn btn-md full-width bg-dark text-light fs-md ft-medium">Create An Account</button>
                                        </div>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </section>

                </div>
                <ToastContainer />
            </main >

        </div >
    )
}
